services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
